import { GoogleGenAI, Modality, GenerateContentResponse } from "@google/genai";

class ImageGenerationService {
    private ai: GoogleGenAI;

    constructor() {
        // The API key MUST be obtained from the environment variable.
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            throw new Error("The API_KEY environment variable is missing in your backend environment.");
        }
        this.ai = new GoogleGenAI({ apiKey });
    }

    /**
     * Generates images using the Imagen 4 model via the Gemini API.
     * @param prompt The base prompt for the image.
     * @param characterDescription An optional description for character consistency.
     * @param aspectRatio The desired aspect ratio of the image.
     * @param sampleCount The number of images to generate.
     * @returns A promise that resolves to an array of base64 encoded image strings.
     */
    public async generateImage(
        prompt: string,
        characterDescription: string | null,
        aspectRatio: string = '1:1',
        sampleCount: number = 1
    ): Promise<string[]> {
        
        // This logic is moved from your frontend to ensure consistency.
        const finalPrompt = characterDescription
            ? `${prompt}. The main character is: ${characterDescription}. Style: cinematic. IMPORTANT: Ensure the character in this image matches this description precisely.`
            : prompt;

        console.log(`Attempting to generate image for final prompt: "${finalPrompt}"`);

        try {
            const response: GenerateContentResponse = await this.ai.models.generateContent({
                model: 'gemini-2.5-flash-image',
                contents: {
                    parts: [{ text: finalPrompt }],
                },
                config: {
                    // CORRECT: Specify that the desired response is an image
                    responseModalities: [Modality.IMAGE],
                },
            });
            
            const images: string[] = [];
            if (response.candidates && response.candidates.length > 0) {
                for (const part of response.candidates?.[0]?.content?.parts ?? []) {
                    if (part.inlineData) {
                        images.push(part?.inlineData?.data ?? '');
                    }
                }
            }

            if (images.length > 0) {
                return images;
            } else {
                 throw new Error('No images were generated by the model.');
            }

        } catch (error: any) {
            console.error("Error generating image with @google/genai:", error.message);
            throw new Error(`Failed to generate image: ${error.message}`);
        }
    }
}

export const imageGenerationService = new ImageGenerationService(); 